
-- @BEGIN REFERENTIAL INTEGRITY CONSTRAINTS
ALTER TABLE `ORCA_BOAT` 		DROP FOREIGN KEY `FK_BOAT_BOAT_TYPE`      ;
ALTER TABLE `ORCA_ACCOUNT` 		DROP FOREIGN KEY `FK_ACCOUNT_ROWING_LEVEL`;
ALTER TABLE `ORCA_RESERVATION` 	DROP FOREIGN KEY `FK_RESERVATION_BOAT` 	  ;
ALTER TABLE `ORCA_RESERVATION` 	DROP FOREIGN KEY `FK_RESERVATION_ACCOUNT` ;
-- @END REFERENTIAL INTEGRITY CONSTRAINTS
