USE ORCA;

-- @BEGIN `ORCA_ACCOUNT`
DROP TABLE IF EXISTS `ORCA_ACCOUNT`;

CREATE TABLE `ORCA_ACCOUNT`
(
	`ACCOUNT_ID` 	CHAR(36) 		NOT NULL                ,
	`FULL_NAME` 	VARCHAR(255) 	NOT NULL                ,
	`EMAIL` 		VARCHAR(255) 	NOT NULL  	UNIQUE      ,
	`PASSWORD` 		VARCHAR(255) 	NOT NULL                ,
	`PHONE` 		VARCHAR(255) 	NOT NULL                ,
	`BIRTH_DATE` 	DATE 			DEFAULT 	'1970-01-01',
	`CAN_SWIM` 		TINYINT(1) 		DEFAULT 	'0'         ,
	`TERM_AGREED` 	TINYINT(1) 		DEFAULT 	'0'         ,
	`LEVEL`			VARCHAR(255)	DEFAULT 	'BEGINNER'  ,
	PRIMARY KEY (`ACCOUNT_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_turkish_ci;
-- @END `ORCA_ACCOUNT`


-- @BEGIN `ORCA_ROWING_LEVEL`
DROP TABLE IF EXISTS `ORCA_ROWING_LEVEL`;

CREATE TABLE `ORCA_ROWING_LEVEL`
(
	`ROWING_LEVEL_NAME`	VARCHAR(255) NOT NULL,
	PRIMARY KEY (`ROWING_LEVEL_NAME`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_turkish_ci;
-- @END `ORCA_ROWING_LEVEL`


-- @BEGIN `ORCA_BOAT_TYPE`
DROP TABLE IF EXISTS `ORCA_BOAT_TYPE`;

CREATE TABLE `ORCA_BOAT_TYPE`
(
	`BOAT_TYPE_NAME`	VARCHAR(255) NOT NULL,
	PRIMARY KEY (`BOAT_TYPE_NAME`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_turkish_ci;
-- @END `ORCA_BOAT_TYPE`


-- @BEGIN `ORCA_BOAT`
DROP TABLE IF EXISTS `ORCA_BOAT`;

CREATE TABLE `ORCA_BOAT`
(
	`BOAT_ID` 		CHAR(36) 		NOT NULL  	   ,
	`BOAT_NAME` 	VARCHAR(255) 	NULL 		   ,
	`BOAT_TYPE` 	VARCHAR(255) 	NOT NULL	   ,
	`RESERVABLE`	TINYINT(1) 		DEFAULT 	'1',	
	PRIMARY KEY (`BOAT_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_turkish_ci;
-- @END `ORCA_BOAT`


-- @BEGIN `ORCA_RESERVATION`
DROP TABLE IF EXISTS `ORCA_RESERVATION`;

CREATE TABLE `ORCA_RESERVATION`
(
	`RESERVATION_ID` 	CHAR(36) 		NOT NULL  					 ,	
	`RESERVATION_DATE`	DATE 			NOT NULL DEFAULT '1970-01-01',
	`RESERVATION_TIME`	TIME 			NOT NULL DEFAULT '00:00'  ,
	`BOAT_RESERVED`		CHAR(36) 		NOT NULL					 ,
	`MEMBER_BOOKED`		CHAR(36) 		NOT NULL					 ,
	PRIMARY KEY (`RESERVATION_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_turkish_ci;
-- @END `ORCA_RESERVATION`

-- @BEGIN `ORCA_WORKING_HOURS`
DROP TABLE IF EXISTS `ORCA_OPERATING_HOUR`;

CREATE TABLE `ORCA_OPERATING_HOUR`
(
	`WORKING_HOUR` TIME DEFAULT '00:00',
	PRIMARY KEY( `WORKING_HOUR` )
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_turkish_ci;
-- @END `ORCA_OPERATING_HOUR`
