
-- @BEGIN REFERENTIAL INTEGRITY CONSTRAINTS
ALTER TABLE `ORCA_BOAT` 		ADD CONSTRAINT `FK_BOAT_BOAT_TYPE` 			FOREIGN KEY (`BOAT_TYPE`) 		REFERENCES `ORCA_BOAT_TYPE` 	(`BOAT_TYPE_NAME`)		ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `ORCA_ACCOUNT` 		ADD CONSTRAINT `FK_ACCOUNT_ROWING_LEVEL` 	FOREIGN KEY (`LEVEL`) 			REFERENCES `ORCA_ROWING_LEVEL`	(`ROWING_LEVEL_NAME`)	ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `ORCA_RESERVATION` 	ADD CONSTRAINT `FK_RESERVATION_BOAT` 		FOREIGN KEY (`BOAT_RESERVED`) 	REFERENCES `ORCA_BOAT`			(`BOAT_ID`) 			ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `ORCA_RESERVATION` 	ADD CONSTRAINT `FK_RESERVATION_ACCOUNT`		FOREIGN KEY (`MEMBER_BOOKED`) 	REFERENCES `ORCA_ACCOUNT`		(`ACCOUNT_ID`) 			ON DELETE CASCADE ON UPDATE CASCADE;
-- @END REFERENTIAL INTEGRITY CONSTRAINTS
